// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDENNQ-wU5YtkGL2t6gqEpKe8oGIhMS0e0',
    appId: '1:512023659634:web:9ef868ee4923e680b12eeb',
    messagingSenderId: '512023659634',
    projectId: 'loan-manager-4d5cc',
    authDomain: 'loan-manager-4d5cc.firebaseapp.com',
    storageBucket: 'loan-manager-4d5cc.appspot.com',
    measurementId: 'G-CBFHB0CS27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv5zZs9aGE-L0FUY2UKAMK67irlgR3RzE',
    appId: '1:76509719502:android:63caec1b2870d4fac7d99f',
    messagingSenderId: '76509719502',
    projectId: 'mobile-loan-app',
    storageBucket: 'mobile-loan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS7TOCT5d7iMqlrQf1onCf2VPpr83tdHQ',
    appId: '1:512023659634:ios:b65cf958fc29708cb12eeb',
    messagingSenderId: '512023659634',
    projectId: 'loan-manager-4d5cc',
    storageBucket: 'loan-manager-4d5cc.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS7TOCT5d7iMqlrQf1onCf2VPpr83tdHQ',
    appId: '1:512023659634:ios:15f71fc184b5765bb12eeb',
    messagingSenderId: '512023659634',
    projectId: 'loan-manager-4d5cc',
    storageBucket: 'loan-manager-4d5cc.appspot.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
